/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/magic-link/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить magic link на email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Письмо отправлено (всегда 202 чтобы не утекать существование email) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить токен из письма и получить сессию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Успешный логин */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description JWT, живёт 15 минут */
                            access_token: string;
                            /** Format: date-time */
                            access_expires_at: string;
                            /** @description opaque, живёт 30 дней */
                            refresh_token: string;
                            /** Format: date-time */
                            refresh_expires_at: string;
                            user: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Новый access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить сессию (отозвать refresh token) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить свой профиль */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Профиль */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить профиль */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        display_name?: string;
                        /** Format: uri */
                        avatar_url?: string;
                        timezone?: string;
                        /** Format: time */
                        daily_push_time?: string;
                        daily_push_enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description Обновлённый профиль */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить аватар */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description Профиль с обновлённым avatar_url */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список тредов пользователя
         * @description Threads ordered freshest-first by `updated_at`. Pagination —
         *     keyset на `(updated_at, id)`. Передавайте `next_cursor` из
         *     предыдущего ответа чтобы получить более старую страницу.
         *     Опаковый формат — клиенту парсить нельзя.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список тредов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Conversation"][];
                            /** @description Передать следующим запросом; отсутствие — больше нет страниц */
                            next_cursor?: string | null;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        /** Создать новый тред */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Новый тред */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        /**
         * Получить тред со страницей сообщений
         * @description Возвращает тред + страницу сообщений в хронологическом порядке (старые сверху).
         *     Курсор семантически — "загрузить старее": клиент держит самое старое
         *     видимое сообщение и передаёт его cursor чтобы получить страницу под ним.
         *     `next_cursor` всегда якорится на самом старом возвращённом сообщении;
         *     пустой/отсутствующий — больше нет истории.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Тред с сообщениями */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            conversation?: components["schemas"]["Conversation"];
                            messages?: components["schemas"]["Message"][];
                            /** @description Передать следующим запросом для загрузки более старой истории; отсутствие — конец */
                            next_cursor?: string | null;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отправить сообщение в тред.
         *     Сервер: (1) сохраняет реплику, (2) вызывает LLM extraction → создаёт/обновляет узлы и связи,
         *     (3) опционально задаёт уточняющий вопрос (см. H13), (4) возвращает обновлённое состояние.
         *
         *     Поддерживает текст и аудио (multipart/form-data для аудио).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Текст сообщения */
                        content: string;
                    };
                    "multipart/form-data": {
                        /** @description Текст (опц., если есть audio — может быть пустым) */
                        content?: string;
                        /**
                         * Format: binary
                         * @description Аудиофайл для транскрипции через Whisper
                         */
                        audio?: string;
                    };
                };
            };
            responses: {
                /** @description Ответ AI и обновлённые узлы */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user_message: components["schemas"]["Message"];
                            /** @description Уточняющий вопрос или подтверждение, может быть null */
                            assistant_message: components["schemas"]["Message"];
                            extracted_nodes: components["schemas"]["Node"][];
                            extracted_edges?: components["schemas"]["Edge"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Стримящаяся версия `/conversations/{id}/messages`. Возвращает SSE
         *     с последовательностью событий: `user_stored` (сразу после коммита
         *     пользовательского сообщения) → `delta` × N (фрагменты ответа
         *     ассистента) → `final` (оба сохранённых сообщения). При сетевой
         *     или provider-ошибке — `error` (фатально, поток закрывается).
         *
         *     Используется фронтом для UX-маскировки латентности LLM. Не-стрим
         *     endpoint остаётся для скриптов и не-браузерных клиентов.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                    };
                };
            };
            responses: {
                /** @description SSE-поток событий чата */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить граф для визуализации (timeline-граф H16)
         * @description Возвращает окно узлов пользователя плюс рёбра, **оба конца которых**
         *     попадают в это окно (висячие рёбра не отдаются — UI их всё равно
         *     не рендерит). Soft-deleted узлы исключаются.
         *
         *     MVP: фильтры `type` (повторяемый) и `since`. `from/to/min_activation`
         *     и курсорная пагинация — отложены до Фазы 5/6.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Фильтр по типам узлов. CSV: `?type=person,event`. */
                    type?: components["schemas"]["NodeType"][];
                    /** @description Нижняя граница `created_at` (RFC3339) */
                    since?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Узлы и рёбра окна */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nodes: components["schemas"]["Node"][];
                            edges: components["schemas"]["Edge"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поиск узлов пользователя по тексту или семантике (revival H11).
         *     text — ILIKE+trgm, semantic — cosine distance по embedding.
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    mode?: "text" | "semantic";
                    /** @description Фильтр по типам узлов. CSV или повтор параметра. */
                    type?: ("thought" | "idea" | "memory" | "dream" | "emotion" | "task" | "event" | "person" | "place" | "topic" | "time")[];
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ранжированный список узлов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nodes: components["schemas"]["Node"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Один узел + его 1-hop окружение (входящие/исходящие edges и
         *     соседние узлы). Используется фронтом для панели деталей при
         *     клике по узлу графа.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Узел и его соседи */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            node: components["schemas"]["Node"];
                            edges: components["schemas"]["Edge"][];
                            neighbors: components["schemas"]["Node"][];
                        };
                    };
                };
                /** @description Узел не найден или не принадлежит пользователю */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Свободный текстовый запрос → ответ с привязкой подстрок к узлам графа.
         *     Подробности и контракт: wiki/recall-mechanics.md.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                        /** @description BCP-47 / двухбуквенный код. Default `ru`. */
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Ответ с подсветкой */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            answer: string;
                            spans: {
                                /** @description Rune-offset (включительно). */
                                start: number;
                                /** @description Rune-offset (исключительно). */
                                end: number;
                                node_ids: string[];
                            }[];
                            nodes: components["schemas"]["Node"][];
                            lang: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recall/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Стримящаяся версия `/recall`. Возвращает SSE с событиями:
         *     `meta` (язык, число anchors/candidates) → `candidates` (узлы целиком,
         *     чтобы UI начал рендер карточек до завершения LLM) → `delta` × N
         *     (фрагменты ответа в рунах) → `final` (валидированные answer + spans
         *     + ссылки на узлы). При ошибке — `error`.
         *
         *     Spans передаются только в `final`: rune-offsets можно валидировать
         *     только против полной строки ответа.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description SSE-поток событий recall */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        /** Получить узел с его связями */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    node_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Узел */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            node?: components["schemas"]["Node"];
                            edges?: components["schemas"]["Edge"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Удалить узел (soft-delete; для биографии остаётся) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    node_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Редактировать узел (текст, тип, дата) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    node_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        content?: string;
                        type?: components["schemas"]["NodeType"];
                        /** Format: date-time */
                        occurred_at?: string | null;
                        pinned?: boolean;
                    };
                };
            };
            responses: {
                /** @description Обновлённый узел */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/nodes/{node_id}/revive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Воскресить затухший узел (поднять activation до 1.0). См. H11. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    node_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Узел с обновлённым activation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить файл (фото/аудио) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /**
                         * Format: uuid
                         * @description Привязать к узлу (опц.)
                         */
                        node_id?: string;
                    };
                };
            };
            responses: {
                /** @description Загруженный media */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Media"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        /** Получить metadata + presigned URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    media_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Media */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Media"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Удалить media */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    media_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resurfacing/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить персонализированный feed proactive напоминаний.
         *     Сервер выбирает узлы по триггерам H8: годовщины, открытые петли, паттерны.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список напоминаний */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["ResurfacingItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resurfacing/{event_id}/engage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отметить что пользователь взаимодействовал с напоминанием */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    event_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resurfacing/{event_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отклонить напоминание (не показывать снова) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    event_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example INVALID_REQUEST */
            code: string;
            /** @example Email is required */
            message: string;
            details?: Record<string, never>;
        };
        /** @enum {string} */
        NodeType: "thought" | "idea" | "memory" | "dream" | "emotion" | "task" | "event" | "person" | "place" | "topic" | "time";
        /** @enum {string} */
        EdgeType: "part_of" | "mentions" | "related_to" | "triggered_by" | "evolved_into" | "about";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name?: string | null;
            /** Format: uri */
            avatar_url?: string | null;
            /** @example Europe/Moscow */
            timezone?: string;
            /**
             * Format: time
             * @example 21:00
             */
            daily_push_time?: string | null;
            daily_push_enabled?: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Node: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["NodeType"];
            title?: string | null;
            content?: string | null;
            /** @description Type-specific поля (см. db-schema.md) */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Когда произошло (для memory, event). Может быть null для мечт/целей/принципов.
             */
            occurred_at?: string | null;
            /** @enum {string|null} */
            occurred_at_precision?: "day" | "month" | "year" | null;
            /**
             * Format: float
             * @description Вес узла (0=затух, 1=активен). См. H11, H18.
             */
            activation: number;
            pinned?: boolean;
            /**
             * Format: uuid
             * @description Сообщение из чата, из которого узел был извлечён (если применимо).
             */
            source_message_id?: string | null;
            /**
             * Format: uri
             * @description Опциональное изображение для визуального представления узла в графе.
             *     Если задано — узел рендерится как круглое фото; если нет — как цветной кружок по типу (H14).
             *     На MVP заполняется seed-данными или внешними URL'ами; полноценный upload-pipeline — Фаза 5.
             */
            image_url?: string | null;
            media?: components["schemas"]["Media"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Edge: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            source_id: string;
            /** Format: uuid */
            target_id: string;
            type: components["schemas"]["EdgeType"];
            /** Format: float */
            weight: number;
            /** Format: date-time */
            created_at?: string;
        };
        Media: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "image" | "audio" | "video";
            /**
             * Format: uri
             * @description Presigned URL (живёт 1 час)
             */
            url: string;
            /** Format: uri */
            thumbnail_url?: string | null;
            mime_type?: string;
            /** Format: int64 */
            size_bytes?: number;
            metadata?: Record<string, never>;
        };
        Conversation: {
            /** Format: uuid */
            id: string;
            title?: string | null;
            /** Format: date-time */
            last_message_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** Format: uri */
            audio_url?: string | null;
            is_clarifying_question?: boolean;
            /** @description Какие узлы создались/обновились из этого сообщения */
            extracted_node_ids?: string[];
            /** Format: date-time */
            created_at: string;
        };
        ResurfacingItem: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "anniversary" | "open_loop" | "pattern" | "mood" | "random";
            node: components["schemas"]["Node"];
            /**
             * @description Текст для показа пользователю
             * @example Полгода назад ты записал мысль про Тайланд. Что с этим?
             */
            message?: string;
            /** Format: date-time */
            shown_at: string;
        };
    };
    responses: {
        /** @description Не авторизован */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Невалидный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ресурс не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
